// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJscq937rvV3NPrjkPv18oxyxqRVF3Eoo',
    appId: '1:70919108841:web:fb6c3d5063f3819bebd878',
    messagingSenderId: '70919108841',
    projectId: 'eventoapp-aeee4',
    authDomain: 'eventoapp-aeee4.firebaseapp.com',
    storageBucket: 'eventoapp-aeee4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCicI7VWQvbCrd8x5IU3iidMF94RCuu1eg',
    appId: '1:70919108841:android:3c75ba9c90588e41ebd878',
    messagingSenderId: '70919108841',
    projectId: 'eventoapp-aeee4',
    storageBucket: 'eventoapp-aeee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7ZNbHe3r4pTNooZXfbpRsHqE5U7qo3c',
    appId: '1:70919108841:ios:1c9d41209e7cd8eaebd878',
    messagingSenderId: '70919108841',
    projectId: 'eventoapp-aeee4',
    storageBucket: 'eventoapp-aeee4.appspot.com',
    iosBundleId: 'com.example.itu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7ZNbHe3r4pTNooZXfbpRsHqE5U7qo3c',
    appId: '1:70919108841:ios:9d59e3ce97e9f497ebd878',
    messagingSenderId: '70919108841',
    projectId: 'eventoapp-aeee4',
    storageBucket: 'eventoapp-aeee4.appspot.com',
    iosBundleId: 'com.example.itu.RunnerTests',
  );
}
